### ISSUE TITLE
Opt-in to hacktoberfest

### ISSUE THREAD

**Issue by yoursunny** [named-data/python-ndn#19]
I'd like to contribute to this repository as part of Hacktoberfest. One feature I'd like to contribute is the ability to communicate with a Bluetooth Low Energy (BLE) peripheral, where python-ndn acts as the BLE central.
In order for the Pull Requests to count toward my Hacktoberfest contributions, it is necessary for the maintainer to add `hacktoberfest` as a repository topic. Can you do that?
https://github.com/digitalocean/hacktoberfest/pull/596

**Comment by zjkmxy** [comment]
Sorry I just saw this. Done now.
