### ISSUE TITLE
Lack of Documentation

### ISSUE THREAD

**Issue by justincpresley** [named-data/python-ndn#24]
I am working on a simple project that requires to cache data and to pull and serve from that cache.
However, I am finding it hard to learn how I could do this effectively. 

I saw in other projects, they use a `ndn.name_tree` class called `NameTrie()` but could not find any documentation on `ndn.name_tree` in the docs nor its related classes/functions.

Is there a simple use example that you could point me to or documentation I missing that could be helpful OR is this something that needs to be added?
I have only found the class [MemoryCache](https://python-ndn.readthedocs.io/en/latest/src/schema/policies.html#ndn.schema.simple_cache.MemoryCache) so far that might be of use in my quest.

**Comment by zjkmxy** [comment]
> I am working on a simple project that requires to cache data and to pull and serve from that cache.

I think [ndn-python-repo](https://github.com/UCLA-IRL/ndn-python-repo) probably fits your requirement if you need a repository.

> I saw in other projects, they use a `ndn.name_tree` class called `NameTrie()` but could not find any documentation on `ndn.name_tree` in the docs nor its related classes/functions.

`NameTrie` was supposed to be used internally, and it's just a patch to [pygtrie](https://pygtrie.readthedocs.io/en/latest/).
If you want to use it, please refer to pygtrie's documentation.

> I have only found the class [MemoryCache](https://python-ndn.readthedocs.io/en/latest/src/schema/policies.html#ndn.schema.simple_cache.MemoryCache) so far that might be of use in my quest.

This part is experimental now. It may be changed in the future.
