### ISSUE TITLE
prepare_data, sqlite malformed

### ISSUE THREAD

**Issue by killerdbob** [named-data/python-ndn#36]
I try to preare_data, and sometimes sqlite will scream.
![cf022bde4aa6abc03c2d70f6795c68c](https://user-images.githubusercontent.com/25005010/146173566-9747a832-1385-496a-ac15-2090fc4ac472.png)

**Comment by zjkmxy** [comment]
Hello. This seems to be a database problem. Could you please create a new ndn-cxx Keychain and try again?

**Comment by killerdbob** [comment]
thx for your reply !!!
maybe the key is rotten? 

![46a8dcd71033ab565cee7eff2f3a335](https://user-images.githubusercontent.com/25005010/146173927-86deed75-d4bb-4541-aa04-c0faf561ab67.png)

**Comment by zjkmxy** [comment]
I'm not sure. This seems to be an exception thrown by `sqlite3` module and I have no idea on why it happens.
Your screenshot looks strange to me because identity name is typically a UTF8 string. But if it contains multiple name components, the output could contain non-English character.

**Comment by killerdbob** [comment]
OK, after I change my environment to ubuntu, this bug disappear. Before, I was using alpine
