### ISSUE TITLE
In 0.3, receive no interest

### ISSUE THREAD

**Issue by killerdbob** [named-data/python-ndn#37]
In version 0.3 and 0.3a1*, my app receive no interest, and I use ndndump to monitor the traffic, I am sure my machine receive the interest. The route has registered into nfd.
However, In version 0.3a1.post3, it works.

**Comment by zjkmxy** [comment]
One possible reason is that we moved to Naming Convention Rev03 in post4. Can you confirm if you are using this?

**Comment by killerdbob** [comment]
Thank you, you are right, after I usr name convention 3 of ndnts library, it works.
