### ISSUE TITLE
Add remote prefix registration support

### ISSUE THREAD

**Issue by GlassyYang** [named-data/python-ndn#38]
at current version of python-ndn, NDNApp only supports local prefix registration because `make_command` function hardcoded nfd's manage prefix into source code, which is `/localhost/nfd`. If we want to implement remote prefix registration, we have to extend `NDNApp `,  override `register` and `unregister` method and copy source code of  `make_command` method into our source code, and changing manage prefix from `/localhost/nfd` to `/localhop/nfd`.
such a solution looks prefect but if python-ndn support remote prefix registration I think it's better.

**Comment by zjkmxy** [comment]
Handled in PR #41
