### ISSUE TITLE
API Support: Exclude Filter + YaNFD

### ISSUE THREAD

**Issue by justincpresley** [named-data/python-ndn#42]
I recently ran into an application use case (when coding a library for python-ndn) involving an ``Exclude filter`` which from my understanding allows me to express a (multicast) interest and not receive the data packets I put within the filter. From the looks of how it is implemented in ndn-cxx, a interest has a ``selector`` parameter which can take this filter and more.

In addition, is YaNFD supported or planned to be? Perhaps there could be a argument to pass to NDNApp() which specify the forwarder type?

**Comment by cawka** [comment]
Exclude and all selectors were removed from the protocol. You need an app level dolition to yourt task
