### ISSUE TITLE
How to add new signing algorithm in python-ndn?

### ISSUE THREAD

**Issue by killerdbob** [named-data/python-ndn#52]
Hi, 
     I would like to add a new feature to python-ndn. For now, python-ndn only has ecdsa, and I would like to add sm2 which is also an asymmetric encryption algorithm. Moreover, I would like to add sm3 which is a hash algorithm. So, how to do these in an easy way?

**Comment by zjkmxy** [comment]
To sign a packet using your algorithm, you need to write a [Signer](https://python-ndn.readthedocs.io/en/latest/src/security/security.html#signer) and [passes it to the encoding function](https://python-ndn.readthedocs.io/en/latest/src/app.html#signature).
You may refer to existing signer, such as the [ECDSA one](https://github.com/named-data/python-ndn/blob/master/src/ndn/security/signer/sha256_ecdsa_signer.py).

To verify the signature, you need to write a [Validator](https://python-ndn.readthedocs.io/en/latest/src/security/security.html#validator) and pass it as the `validator` of function calls such as `register` or `express_interest`.
You may refer to [existing ones](https://github.com/named-data/python-ndn/blob/master/src/ndn/security/validator/known_key_validator.py).

However, the default SQLite KeyChain does not support new key types, so you will be unable to use other [keyword arguments related to signature](https://github.com/named-data/python-ndn/blob/master/src/ndn/security/validator/known_key_validator.py) such as `identity`, `key` and `cert`.
If you still want to have a KeyChain, you may implement [KeyChain class](https://python-ndn.readthedocs.io/en/latest/src/security/security.html#keychain), but I think this is overshooting.

**Comment by killerdbob** [comment]
thank you, I will try to do these

**Comment by zjkmxy** [comment]
FYI: #54
