### ISSUE TITLE
Opt-in to hacktoberfest

### ISSUE THREAD

**Issue by yoursunny** [named-data/python-ndn#55]
I'd like to contribute to this repository as part of Hacktoberfest.
While I'm unfamiliar with the Python language, I would perform documentation improvements.
In order for the Pull Requests to count toward my Hacktoberfest contributions, it is necessary for the maintainer to add `hacktoberfest` as a repository topic.
Can you do that?
https://hacktoberfest.com/participation/#maintainers

**Comment by zjkmxy** [comment]
Adding topic complete. I will not add CONTRIBUTING.md since named-data organization has a global one.

**Comment by yoursunny** [comment]
Yes, topic is sufficient.
