### ISSUE TITLE
How to remote register and auto readvertising?

### ISSUE THREAD

**Issue by killerdbob** [named-data/python-ndn#58]
I remotely register into NFD, but the application could not auto advertise prefix. I notice that the application route `origin=app`. 
I would like to know how to change `origin=app` to  `origin=client` ?

**Comment by zjkmxy** [comment]
> I remotely register into NFD, but the application could not auto advertise prefix. 

I'm not sure if people are still using the Automatic Prefix Propagation protocol. I have never used it myself.
There is an article that may help you set it up: [Let the World Reach Your NFD](https://yoursunny.com/t/2016/nfd-prefix/).

> I notice that the application route `origin=app`. I would like to know how to change `origin=app` to `origin=client` ?

By [NFD management protocol](https://redmine.named-data.net/projects/nfd/wiki/RibMgmt#Register-a-route), I think an application should register a route with origin `app`. My personal view is that the origin `client` only indicates an route *was created* by an auto propagation. It is not how NFD decides which prefix to propagate.

**Comment by killerdbob** [comment]
ok， thanks
