### ISSUE TITLE
Tag the source

### ISSUE THREAD

**Issue by fabaff** [named-data/python-ndn#65]
Could you please tag the source again? This allows distributions to get the complete source from GitHub if they want.

PyPI has 0.3-3 while GitHub is at 0.3-1

Thanks

**Comment by zjkmxy** [comment]
Done. I should probably write a GitHub trigger for this.

**Comment by zjkmxy** [comment]
I believe [poetry_dynamic_versioning](https://pypi.org/project/poetry-dynamic-versioning/) has solved the problem, so let me close this issue.
